# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1463638524);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 36);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1463638445293");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1463640309293");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1463638411541");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1463642011541");
user_pref("browser.search.countryCode", "IN");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1463638405");
user_pref("browser.slowStartup.averageTime", 2363);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20160407164938");
user_pref("browser.startup.homepage_override.mstone", "45.0.2");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":3}");
user_pref("browser.taskbar.lastgroupid", "E7CF176E110C211B");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"pocket-button\",\"downloads-button\",\"home-button\",\"loop-button\"]},\"seen\":[\"loop-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\"],\"currentVersion\":5,\"newElementCount\":0}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1463724803278");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1463638465219");
user_pref("datareporting.policy.firstRunTime", "1463638403277");
user_pref("datareporting.sessions.current.activeTicks", 19);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1535);
user_pref("datareporting.sessions.current.main", 49);
user_pref("datareporting.sessions.current.sessionRestored", 2386);
user_pref("datareporting.sessions.current.startTime", "1463638402824");
user_pref("datareporting.sessions.current.totalTime", 199);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"1.1.14\",\"type\":\"extension\",\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\features\\\\loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.0.2");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.0.2");
user_pref("extensions.lastPlatformVersion", "45.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\features\\\\loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1.14\",\"st\":1461648179536}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.0.2\",\"st\":1461648179546}},\"winreg-app-global\":{\"otis@digitalpersona.com\":{\"d\":\"C:\\\\Program Files (x86)\\\\Hewlett-Packard\\\\HP ProtectTools Security Manager\\\\Bin\\\\FirefoxExt\",\"e\":false,\"v\":\"5.0.0.4182\",\"st\":1442086702926,\"mt\":1258133540000}}}");
user_pref("gecko.buildID", "20160407164938");
user_pref("gecko.mstone", "45.0.2");
user_pref("gfx.crash-guard.d3d11layers.appVersion", "45.0.2");
user_pref("gfx.crash-guard.d3d11layers.deviceID", "0x0042");
user_pref("gfx.crash-guard.d3d11layers.driverVersion", "8.15.10.1968");
user_pref("gfx.crash-guard.d3d11layers.feature-d2d", false);
user_pref("gfx.crash-guard.d3d11layers.feature-d3d11", true);
user_pref("gfx.crash-guard.status.d3d11layers", 2);
user_pref("gfx.crash-guard.status.d3d9video", 2);
user_pref("media.gmp-eme-adobe.abi", "x86-msvc-x64");
user_pref("media.gmp-eme-adobe.lastUpdate", 1463638470);
user_pref("media.gmp-eme-adobe.version", "15");
user_pref("media.gmp-gmpopenh264.abi", "x86-msvc-x64");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1463638471);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20160407164938");
user_pref("media.gmp-manager.lastCheck", 1463638466);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("sanity-test.device-id", "0x0042");
user_pref("sanity-test.driver-version", "8.15.10.1968");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "45.0.2");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1463638402);
user_pref("toolkit.telemetry.cachedClientID", "33fab2da-32bc-4045-9e90-cd1e375a8b64");
user_pref("toolkit.telemetry.previousBuildID", "20160407164938");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
