# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 31);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "IN");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.defaultBrowserCheckCount", 1);
user_pref("browser.slowStartup.averageTime", 1959);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20151216175450");
user_pref("browser.startup.homepage_override.mstone", "43.0.1");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":3}");
user_pref("browser.taskbar.lastgroupid", "E7CF176E110C211B");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1461670181163");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1461583842999");
user_pref("datareporting.policy.firstRunTime", "1461583781163");
user_pref("datareporting.sessions.current.activeTicks", 14);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1334);
user_pref("datareporting.sessions.current.main", 59);
user_pref("datareporting.sessions.current.sessionRestored", 2170);
user_pref("datareporting.sessions.current.startTime", "1461583780821");
user_pref("datareporting.sessions.current.totalTime", 95);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:43.0.1");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "43.0.1");
user_pref("extensions.lastPlatformVersion", "43.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"43.0.1\",\"st\":1458628516844,\"mt\":1458628516805}},\"winreg-app-global\":{\"otis@digitalpersona.com\":{\"d\":\"C:\\\\Program Files (x86)\\\\Hewlett-Packard\\\\HP ProtectTools Security Manager\\\\Bin\\\\FirefoxExt\",\"e\":false,\"v\":\"5.0.0.4182\",\"st\":1442086702926,\"mt\":1258133540000}}}");
user_pref("gecko.buildID", "20151216175450");
user_pref("gecko.mstone", "43.0.1");
user_pref("gfx.crash-guard.d3d11layers.appVersion", "43.0.1");
user_pref("gfx.crash-guard.d3d11layers.deviceID", "0x0042");
user_pref("gfx.crash-guard.d3d11layers.driverVersion", "8.15.10.1968");
user_pref("gfx.crash-guard.d3d11layers.feature-d2d", false);
user_pref("gfx.crash-guard.d3d11layers.feature-d3d11", true);
user_pref("gfx.crash-guard.status.d3d11layers", 2);
user_pref("gfx.crash-guard.status.d3d9video", 2);
user_pref("media.gmp-eme-adobe.abi", "x86-msvc");
user_pref("media.gmp-eme-adobe.lastUpdate", 1461583848);
user_pref("media.gmp-eme-adobe.version", "15");
user_pref("media.gmp-gmpopenh264.abi", "x86-msvc");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1461583849);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20151216175450");
user_pref("media.gmp-manager.lastCheck", 1461583844);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("sanity-test.device-id", "0x0042");
user_pref("sanity-test.driver-version", "8.15.10.1968");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "43.0.1");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1461583780);
user_pref("toolkit.telemetry.cachedClientID", "d63503f2-0586-45c8-a0b4-74085ca3f751");
user_pref("toolkit.telemetry.previousBuildID", "20151216175450");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
