# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 30);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.cohort", "web.xml");
user_pref("browser.search.countryCode", "IN");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1449029207");
user_pref("browser.slowStartup.averageTime", 3865);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20151029151421");
user_pref("browser.startup.homepage_override.mstone", "42.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":4}");
user_pref("browser.taskbar.lastgroupid", "308046B0AF4A39CB");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1449115603393");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1449029203392");
user_pref("datareporting.sessions.current.activeTicks", 8);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 2284);
user_pref("datareporting.sessions.current.main", 162);
user_pref("datareporting.sessions.current.sessionRestored", 4429);
user_pref("datareporting.sessions.current.startTime", "1449029202737");
user_pref("datareporting.sessions.current.totalTime", 52);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:42.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "42.0");
user_pref("extensions.lastPlatformVersion", "42.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"C:\\\\Program Files\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"42.0\",\"st\":1447992560954,\"mt\":1447992560277}}}");
user_pref("gecko.buildID", "20151029151421");
user_pref("gecko.mstone", "42.0");
user_pref("gfx.blacklist.direct2d", 3);
user_pref("gfx.driver-init.appVersion", "42.0");
user_pref("gfx.driver-init.deviceID", "0x2e42");
user_pref("gfx.driver-init.driverVersion", "8.15.10.2302");
user_pref("gfx.driver-init.feature-d2d", false);
user_pref("gfx.driver-init.feature-d3d11", true);
user_pref("gfx.driver-init.status", 2);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 92258);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("sanity-test.device-id", "0x2e42");
user_pref("sanity-test.driver-version", "8.15.10.2302");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "42.0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1449029202);
user_pref("toolkit.telemetry.cachedClientID", "88ce3e6c-869e-49b8-a8cd-cbbf385db71b");
user_pref("toolkit.telemetry.previousBuildID", "20151029151421");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
